### ISSUE TITLE
On first run, an assignment checking a variable’s initial value can be right even if student code isn’t

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#13]
I wrote an assignment where the student has to define a variable and give it a specific starting value. On the first run, if you just assign any value to a var, the test “health is equal to 100” passes although it shouldn’t.
This happens if you write anything like `var healthvar health = 5` etc. From the second Run, though, the tests work as expected. The test code is:

```gdscript
var health_value = first_node.get("health")
if health_value == 100:  return ""
```

If the student doesn’t write the property, the value should be null and cause the test to fail, but it doesn’t.

**Comment by johnnygossdev** [comment]
Lesson 12 #86 also checks for variable values and comes across this issue.

**Comment by Xananax** [comment]
This is a tad complex to fix, and requires to make a certain number of calls I'm not entirely comfortable doing without opening a discussion.

Firstly, let me expose the problem as succinctly as I can.

## How Script Replacement Currently Works

In [ui/UIPractice.gd:256](https://github.com/GDQuest/learn-gdscript/blob/6aeac8a6b0a9244b116e1d988e2fff74fc96c53f/ui/UIPractice.gd#L256), the node properties are backed up, then the new script is set on the node, then the properties are restored. It looks like this (abbreviated for illustration):

```gdscript
var props := {}

for prop in node.get_property_list():
  props[prop.name] = node.get(prop.name)

node.set_script(script)

for prop in props:
    node.set(prop, props[prop])
```

Before the script is replaced:

1. the old value of the property (`health: 100`) is backed up
2. then the script is replaced by the new (user supplied) script (`health: 10`)
3. then the previous value is restored restored, and erases the new value.

If you remove those lines, the practice works. You can test this in the branch [optionally-restore-node-properties](https://github.com/GDQuest/learn-gdscript/tree/optionally-restore-node-properties), in which I extracted the lines that backup and restore properties.

## The Problem

`_ready` doesn't run a second time. Therefore, _every value that relies on onready_ is `null` when the script loads. This makes it so the branch is a regression on a lot of other scripts, specially those that use `onready` to specify nodes, but also even using simple values.

For example, [course/lesson-3-standing-on-shoulders-of-giants/make-upright/MakeRobotUpright.gd](https://github.com/GDQuest/learn-gdscript/blob/main/course/lesson-3-standing-on-shoulders-of-giants/make-upright/MakeRobotUpright.gd) looks like this:

```gdscript
onready var start_rotation := rotation

func _run():
	rotation = start_rotation
	rotate(0.5)
```

On reload, this script will error out, saying that `cannot set rotation to null`.

## Potential Mitigations:

### 1. Run `_ready()` after reloading the script

I do not remember the implications of this. I remember it wasn't working as expected. We can test it again and get a better understanding of what works or doesn't.

### 2. Create a `_our_ready()` method

We move any `onready` variable in our own custom boostrapping method, and call that in `_ready` (or, alternatively, we call it when setting the scene in the scene player).

- The upside: we can keep most of the app's code working as it does.
- The downside: our exercises script are becoming increasingly not actually "just GDScript" that we're running, but a completely specific API. We might want to think how much of the global namespace we want to invade, and if this philosophy matches our goals. It's possible there's no escape from this, as long as Godot doesn't expose better meta-programming tools, and that we're just fighting an uphill battle trying to not have a specific API.

### 3. Avoid exercises where the user has to set a global variable

Requires some consistency in exercises. Instead of writing:

```gdscript
extends Control

# EXPORT health
var health = 100
# /EXPORT health
```

We'd always write:

```gdscript
extends Control

func _run():
  # EXPORT health
  var health = 100
  # /EXPORT health
```

- The upside: we change absolutely nothing to our current application, only some practices
- The downsides: we cannot present exercises where script-scoped variables can be changed. We have to be careful to never use script-scoped variables. 

### 4. Selectively exclude or keep properties

In the branch  [optionally-restore-node-properties](https://github.com/GDQuest/learn-gdscript/tree/optionally-restore-node-properties), there are two static functions to backup node properties, and restore node properties.

We could backup all properties, but have a filter to skip some properties at restore time. In other words, `health` would be skipped during the restore process. Alternatively, we could select the properties to keep (restore all the `onready` properties, not the rest).

This can be selected either by:

a. adding an PoolStringArray of properties to keep/exclude from the practice resource 
b. parsing the text for `onready` and restoring all of those, excluding the others
c. ? There may be better ways

**Comment by pycbouh** [comment]
> I do not remember the implications of this. I remember it wasn't working as expected. We can test it again and get a better understanding of what works or doesn't.

I don't think there are any implications, the engine specifically has a system for this, you call `request_ready()` on a node. It marks the node as if ready was never called. All those `onready` statements are evaluated as well the moment `_ready` is called.

However, this is only checked upon adding the node to the tree. So you might want to quickly remove and re-add it (which shouldn't break anything, really).

**Comment by Xananax** [comment]
I'll try that, thanks!

> which shouldn't break anything, really

Almost, but signals will be disconnected, right? We'd have to back up those and restore them.

I don't think any practice uses signals for the time being, but it'd still be something to keep in mind.

**Comment by pycbouh** [comment]
I don't see why the signals would be disconnected on removing the node from the tree. But you may have the opposite problem, as ready is often used to connect signals, so they will be connected already and you need to guard them in ready with `is_connected()`.

**Comment by Xananax** [comment]
yep, removing and re-adding the nodes works, at least for the current exercises! Thanks
