### ISSUE TITLE
Add smooth scrolling support

### ISSUE THREAD

**Issue by thayusmc** [GDQuest/learn-gdscript#164]
**Describe the problem you're trying to solve.**

When you scroll down using the mouse wheel, the page juts down, instead of scrolling smoothly.

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

I think that making the scroll smoother would make the text easier to read, since when it juts down, you lose your place and it takes a quick second to get back to where you were.

**Comment by NathanLovato** [comment]
@pycbouh and I discussed this. This feature should most likely be part of Godot as scrollbars are implemented in Godot and directly react to mouse wheel events. So it's something we consider work to do on the engine rather than this app.

For now, we won't try to add this to the app itself with GDScript.

**Comment by SpyrexDE** [comment]
I also think this is a big problem. I developed my own [SmoothScroll](https://github.com/SpyrexDE/SmoothScroll) plugin some time ago. However, it is far from complete, but could be used as a basis for such a feature.

**Comment by SpyrexDE** [comment]
I will work on that, already making great progress!

**Comment by NathanLovato** [comment]
Thanks for trying. I've assigned you to the issue. Just to check, @pycbouh, what do you think? Do you think we should only do this upstream in Godot, or this would be okay to try in GDScript, client-side?
