### ISSUE TITLE
Lesson 12, practice 1: only global variable is valid

### ISSUE THREAD

**Issue by elruiz1993** [GDQuest/learn-gdscript#198]
**Describe the bug**
In lesson 12, the first excercise only is valid if you put angular_speed as a global variable when in the same lesson explains that global and local variables are fine.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 12"
2. Click on 'Clarify code using variables' practice button
3. Set 'var angular_speed = 4' inside func _process(delta)
4. Press 'Run'

**Expected behavior**
GDQuestBoy spins and the lesson is complete.

**Screenshots**

![Captura de pantalla (5)](https://user-images.githubusercontent.com/83378367/151427876-400a6322-b472-4754-a20c-846dc18296e0.png)

**Information about your device (please complete the following information):**
 - Windows 10
 - Browser: Microsoft Edge

**Comment by NathanLovato** [comment]
As mentioned in the practice goal, the variable should be _script-wide_, not local to the function. You're making the variable local to the function here, which is why it doesn't work.

The lesson explains the difference between script-wide and local variables too. It doesn´t say you can use them interchangeably.

We'll see if we can improve the explanation.

**Comment by johnnygossdev** [comment]
I made the text from errors a bit more helpful and improved the practice goals to help with this.
