### ISSUE TITLE
Ch. 6, practice #2 - Accepts wrong solution

### ISSUE THREAD

**Issue by selkaine** [GDQuest/learn-gdscript#206]
**Describe the bug**
After you type in "angle" in the first line's parameter and then input any number or the word "length" in the parameter for "turn_right()", the practice accepts the solution.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Chapter 6's practice 2 "Using Multiple Parameters"
2. Add "angle" to the first line as instructed in the goals section, i.e func draw_corner (length, angle):
3. In the turn_right() parameter, add any number such as 0 or 90 or the word length. i.e turn_right(45)
4. Click Run.
5. Practice accepts solution.

**Expected behavior**
The Checks section says to draw corners of varying sizes and angles. Since I drew the same angle, I expected it to not accept the solution.

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Chrome

**Additional context**
I'm a beginner starting from zero. I don't understand why adding "angle" to the turn_right() parameter caused varying angles. It was not something I thought I needed to do for this practice given in the Chapter 6 lesson, it said we will stick to numbers for the parameters for now.

**Comment by NathanLovato** [comment]
Fixed by 865a565c305803702a9fd59165e40fc7207022af

**Comment by NathanLovato** [comment]
> we will stick to numbers for the parameters for now.

I'll try to rephrase this. Parameters are names for any values passed to a function call. This happens when calling the function. You could call draw_corner() with any numbers. Because the numbers can change on every function call, in the function, we don't use numbers directly: instead, we give those parameters a name.

In this assignment, the names are `length` and `angle`.

When testing your practice, the app calls draw_corner() with different values for length and angle, and it expects your code to produce precise corners with those values.
