### ISSUE TITLE
Fullscreen in Chrome/Firefox disturbs the button detection

### ISSUE THREAD

**Issue by ShalokShalom** [GDQuest/learn-gdscript#208]
**Describe the bug**
When I switch into fullscreen on Firefox 96 on Linux X11, buttons become unresponsive when I hover over them with the cursor and instead they become clickable, when they shouldn't. 

The whole detection of where buttons are is messed up. 

**Expected behavior**
Buttons are clickable when I hover over them in fullscreen. 

**Screenshots**
![Screenshot_20220129_115023](https://user-images.githubusercontent.com/6344099/151658289-2242db63-40d5-4e7e-b829-201099b5a08d.png)

**Information about your device (please complete the following information):**
 - Operating System: KaOS Linux
 - Browser Firefox

**Additional context**
The text and the frame of the button in the applied screenshot are supposed to light up white.

**Comment by ShalokShalom** [comment]
It works just fine in non-fullscreen mode.

**Comment by NathanLovato** [comment]
We have a couple of browser-specific bugs like this one. I don't know why they occur and if we can do anything about them - it may be an issue on Godot's side. Although it could also have to do with our HTML/CSS code. We'll have to investigate.

**Comment by MattHorn25** [comment]
Just adding to the above - I'm experiencing the same issue on Chrome 97.0.4692.99, Windows 10 OS. Various buttons and sliders' active areas don't match their visual elements. This extends to the 'fullscreen' button which, once fullscreen, is no longer clickable because the active area for the 'Report an Issue' link extends across the 'fullscreen' visual element.

**Comment by hecksadecimal** [comment]
Seems like this isn't just an issue with fullscreen mode. 

Firefox 96.0.3 (64-bit) on Manjaro 21.2.2 (Kernel 5.15.12-1-MANJARO)
![image](https://user-images.githubusercontent.com/20251491/151877973-c0148e66-a8f9-4612-8ad5-f6a1e4a97c23.png)

**Comment by johnnygossdev** [comment]
> Just adding to the above - I'm experiencing the same issue on Chrome 97.0.4692.99, Windows 10 OS. Various buttons and sliders' active areas don't match their visual elements. This extends to the 'fullscreen' button which, once fullscreen, is no longer clickable because the active area for the 'Report an Issue' link extends across the 'fullscreen' visual element.

This is my experience too on Firefox / Windows.

https://user-images.githubusercontent.com/3285214/151990012-b6706b0f-b41b-454f-aac9-befecbbabd67.mp4

**Comment by pycbouh** [comment]
Can confirm it being a problem in Chrome on Windows too, only in fullscreen though.

**Comment by johnnygossdev** [comment]
Full screen for me works as intended.

**Comment by ShalokShalom** [comment]
> Seems like this isn't just an issue with fullscreen mode.
> 
> Firefox 96.0.3 (64-bit) on Manjaro 21.2.2 (Kernel 5.15.12-1-MANJARO) ![image](https://user-images.githubusercontent.com/20251491/151877973-c0148e66-a8f9-4612-8ad5-f6a1e4a97c23.png)

Do you run this borderless, or did you just not screenshot your top bar?

**Comment by hecksadecimal** [comment]
> > Seems like this isn't just an issue with fullscreen mode.
> > Firefox 96.0.3 (64-bit) on Manjaro 21.2.2 (Kernel 5.15.12-1-MANJARO) ![image](https://user-images.githubusercontent.com/20251491/151877973-c0148e66-a8f9-4612-8ad5-f6a1e4a97c23.png)
> 
> Do you run this borderless, or did you just not screenshot your top bar?

I just didn't screenshot the top bar, had other tabs open.

**Comment by DavidZajicek** [comment]
I was having this issue and I've done some testing on my end, I believe this is due to scaling/ratio. 
I have the issue while on my 16:10 ratio laptop (running 1920x1200), changing this to 16:9 (1920x1080) the issue is resolved.


I'm running, Windows 10, Version 20H2 19042.1415, Chrome Version 96.0.4664.110 (Official Build) (64-bit).
Non-fullscreen: (same as when in 1920x1080)

![2022-02-02 20_03_21-Learn to Code From Zero with Godot](https://user-images.githubusercontent.com/86643694/152125805-921d8148-1ea2-467c-a586-d8b7d683a2e4.png)

Fullscreen with 16:10 ratio resolution:
![2022-02-02 20_03_57-Learn to Code From Zero with Godot](https://user-images.githubusercontent.com/86643694/152125883-4db23838-fe39-41a2-9eee-b7db438c6c0e.png)
![2022-02-02 20_16_24-Learn to Code From Zero with Godot](https://user-images.githubusercontent.com/86643694/152125885-4c5d5244-1640-48a7-9ff9-6b4bf9d082d7.png)

**Comment by pycbouh** [comment]
Yes, it clearly looks like the hit areas a sized to the entire screen, while the rendered part of the app is properly centered. I'm not sure what we can do about it though, since this smells like a Godot bug. Maybe our elastic canvas is misbehaving, of course.

**Comment by MattHorn25** [comment]
Agreed with other comments above - I previously failed to mention that I'm using an ultrawide screen. It would appear that everyone who's reported the issue so far may be using a nonstandard (ie not 16:9) monitor. So as @pycbouh stated, the hit areas are sized to the entire screen while the rendered part of the app is properly centered.

**Comment by NathanLovato** [comment]
No, that's not an option as this is a bug. The hit areas should match the visuals, but the visuals aren't resizing properly. Even if we drew the boxes, they'd be off as the drawing is off.
