### ISSUE TITLE
Lesson 2: Indentation error not detected

### ISSUE THREAD

**Issue by SaiKiru** [GDQuest/learn-gdscript#216]
**Describe the bug**
Indentation error is only detected if it is less than expected indentation level.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 2 practice
2. Uncomment the `#return`
3. Make sure it is at least 1 indent level
4. You can increase the indent level or mix spaces and tabs

**Expected behavior**
An error for improper indentation

**Screenshots**
This is valid code.
![image](https://user-images.githubusercontent.com/59113205/151803243-778fd897-05f0-4e09-8693-eb733291533c.png)

**Information about your device (please complete the following information):**
 - Operating System: Endeavour OS
 - Browser: Firefox DE

**Additional context**
Lesson 2 talks about errors and how the error messages work in the App. The lab suggests running the code first, which produces an indentation error. It also suggests removing indentation if the user wants, which also produces an indentation error. Over indenting should be an issue too.

**Comment by NathanLovato** [comment]
It's because indenting multiple times is not an error. Technically, the compiler checks changes in indentation level and that lines in a given block are at the same level. So you could indent 10 times after the start of a block, as long as all following lines are indented 10 times, it's okay.

But I don't want to add cognitive load by explaining those little subtleties, I think that'd confuse students getting started with code more than anything at lesson 2.

![image](https://user-images.githubusercontent.com/12694995/151808744-b0bc249d-202b-430d-bdd8-099975911749.png)
