### ISSUE TITLE
Allow for interactive visuals that can take mouse input

### ISSUE THREAD

**Issue by johnnygossdev** [GDQuest/learn-gdscript#245]
**Is your feature request related to a problem? Please describe.**
I'd like to make an interactive visual which uses the mouse so learners can play and visualize vectors.

**Describe the solution you'd like**
Currently something is stealing the input, but I haven't found what.

**Describe alternatives you've considered**
I tried to change the mouse filter on all the control nodes in the scene, `UICore.tscn`, `UILesson.tscn` and `UINavigator.tscn` which I thought would be stealing the mouse input, but I likely missed something.

**Additional context**
Here is a draft of the scene I'd like to implement.

https://user-images.githubusercontent.com/3285214/152155781-1fa6b31c-9f44-4418-8927-8828bceb9b77.mp4

Here is the scene in the lesson.

https://user-images.githubusercontent.com/3285214/152155790-2db320c6-cc0c-41a8-be4d-7fe7dadefe75.mp4

**Comment by NathanLovato** [comment]
I just worked on this a bit. The issue was that ContentBlocks in UILesson was blocking the mouse input. I don't understand why as it was set to Pass - I would expect it to let children grab the input first.

Note that I think for visual examples taking mouse input, we would need something other or more features in RunnableCodeExample. For this you could use the input_event signal in combination with the viewport, but what if your demo needs to rely on _process instead? We might need something that activates the demo only when the user focuses the element.

That's just something to consider at least. For now, I'll clean up my branch and fix the mouse input issue.

**Comment by NathanLovato** [comment]
Any UI element set to stop the mouse will swallow the mouse input before the demo receives the unhandled input or input_event callback, so you had to really make them *all* ignore input. And there were lots of nested controls in the way.

I think it's fine for now, we don't want to block clicks or the mouse in the lessons. If at some point we need to selectively block mouse input, we can have a control selectively toggle between blocking and ignoring mouse input.

Now you should be good to add your vector example to lesson 16 @johnnygossdev
