### ISSUE TITLE
Lesson 3 - Parameter vs Argument

### ISSUE THREAD

**Issue by z0x0936** [GDQuest/learn-gdscript#263]
**Issue description:**
A clear and concise description of what the issue is.

This distinction was drilled so hard into me, that I can't unsee it. When a function is "called", the values passed in are ARGUMENTS. When a function is "defined" any arguments received are defined as PARAMETERS.

```

#defining a function with parameters
func do_something(PARAMETER1, PARAMETER2):
    #doing stuff with parameters

#calling a function with arguments
do_something(ARGUMENT1, ARGUMENT2)
```

**Comment by NathanLovato** [comment]
At this stage, it's not a good idea to make the distinction. It just makes things harder. I guess we can just avoid calling the value passed to the function a parameter and call it a value. But I don't want to be nit-picky about terminology at the expense of the students. Otherwise, you could argue we should talk about methods and not functions, properties rather than variables, etc.
