### ISSUE TITLE
Reporting bugs is complicated and daunting for beginners

### ISSUE THREAD

**Issue by ChrisWhatever1980** [GDQuest/learn-gdscript#333]
**Describe the bug**
Having to register for github might be asking too much of the beginner user. It deterred me from reporting a bug at first.

**To Reproduce**
Click the report bug button in the upper right corner.

**Expected behavior**
I expected a form where the user can enter the sections of the report (the one I am writing right now on github) in separate input fields inside the app. The report is then posted with a generic user to github maybe by using the github issues API.

**Screenshots**
The app itself could then provide the screenshot.

**Information about your device (please complete the following information):**
Windows, Chrome
The app could add this information automatically to the bug report.

**Additional context**
The app could add this information (chapter, task) automatically to the bug report.

**Comment by NathanLovato** [comment]
Already planned, see #150.

Also, please don't report supposed issues on behalf of others. We already take reports and create issues for beginners when they contact us or if they don't want to create a github account.

Lastly, nobody told us they personally had issues or it was too daunting reporting bugs, on Github or otherwise. When people don't want to report issues on github, they already email us or tweet me or post on our discord.
