### ISSUE TITLE
Incorrect solution works

### ISSUE THREAD

**Issue by CanonRouge24** [GDQuest/learn-gdscript#349]
On "Rotating using Delta" in lesson 11 (the first of the two practice problems), the correct solution is

```
func _process (delta):
    rotate(delta * 2)
```

My brain was smol for a moment there and I put
```
func _process (delta):
    delta * rotate(2)
```

which still rotates the character 2 radians clockwise but is not time-dependent.

**Comment by Programmerking7** [comment]
I experienced in lesson 11 in the second practice that the following wrong solution was accepted:

func _process(delta):
	rotate(2 * delta)
	move_local_x(100)

The first time doing this practice, I forgot to multiply the 100 in the move_local_x function by delta as intended by the practice. The code was still accepted regardless. It's funny because it says make it move in a smooth circle and with the above code it just bolts out of the screen immediately and comes back every now and then
