### ISSUE TITLE
Improve app experience in browser

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#37]
- [x] Limit maximum size on large displays
- [x] Add nicer loading bar
- [x] Change the background color
- [x] Make the app full screen when making the browser full screen

**Comment by seppoday** [comment]
I would also improve scrolling with mose wheel. Right now it scrools whole page. That's kinda annoying and not smooth experience.

**Comment by NathanLovato** [comment]
@seppoday in which browser? And on which device? I don't have that in Brave or Firefox here on Linux.

**Comment by seppoday** [comment]
It was Windows and Chrome. But somehow on Brave it is looking fine, so probably nevermind?

**Comment by NathanLovato** [comment]
We'll have to test. As part of this task Xananax is controlling the resizing of the app and preventing overflowing (which can cause the scrolling you experience).

**Comment by dialmove** [comment]
I've found that resizing the window height is reducing the content size, because the margins size is kept as a constant width of the screen. 

Expected behavior in a windowing system would be to reduce the width of the margins until it is almost 0, and only then start to zoom out the column content.

Is it something that can be done with the Godot layout toolkit?  Or maybe the margins could be made part of the html page itself (using the "margin" property of the html canvas container), instead of painting them inside the canvas, so that the browser will resize them naturally?
