### ISSUE TITLE
Add a shortcut to run the code

### ISSUE THREAD

**Issue by xix-xeaon** [GDQuest/learn-gdscript#40]
**Describe the bug**
When you're in a "practice" you should be able to run the code without having to move your mouse. I expected to be able to use Ctrl+Enter to run the code, but it does not run.

**Comment by pycbouh** [comment]
We are discussing having more shortcuts, however, the app and the course is designed for absolute beginners, who would not expect that to be the workflow. So this may end up causing confusion if they do hit a shortcut accidentally.

**Comment by NathanLovato** [comment]
Yup, I was thinking of something more like Ctrl+R or Ctrl+Shift+R. Let's see. In any case, it's not a bug.

**Comment by xix-xeaon** [comment]
I can understand that. I think this would be a good idea though because it makes it more interactive. I was also considering if the app should validate / run the code automatically all the time.

I know my students are sometimes confused when the Godot editor shows errors simply because they've not finished typing, but on the other hand it also gives instant feedback when they make mistakes or get it right.

When you get to the more "complicated" practice problems that have several steps in them, having the run window continuously show what you've done so far is very good feedback.

Maybe ctrl+enter seems like it could be a nice balance (and much easier implemented).

**Comment by pycbouh** [comment]
Any shortcut would be equally easy to implement 🙃 Adding them, however, raises a question of discoverability, as we'd need to teach them to users, whether as a part of the interactive tutorial for the app, or as a separate screen with a cheat sheet.

**Comment by NathanLovato** [comment]
That's the idea, somewhere between #11, #28, and #29.

**Comment by generrosity** [comment]
One vote for 'align with Godot' - you could capture and use "F5" the same way Godot web editor does. Perhaps surface as button hover tip and include in later Godot UI 'why all the funky colours?' lessons. I see you already prevent web F5/F12 functionality.

MSOutlook surfaces this by detecting it, and asking how to act. It otherwise buries the option. For Godot you could capture the control-enter and popup an explaination or feature enablement.

Also, you could surface the same way GitHub surfaces Markdown tips as a subtle icon in a corner. But I like this option the least.
![image](https://user-images.githubusercontent.com/12838061/147721878-e37b36d9-a5c9-4d79-a870-0fa9d6a67062.png)

**Comment by NathanLovato** [comment]
#90 supersedes this
