### ISSUE TITLE
Lesson 20 Looping over arrays bug in Practice 2

### ISSUE THREAD

**Issue by Tharanel7** [GDQuest/learn-gdscript#452]
Error Meassage even if the Code is right

So i had the issue that the Code was correct but i got always the Error that 1 of the Rectangle have the wrong size, even with the Solution code. 

Steps to reproduce the bug:
1. Go to Practice 2 in Lesson 20
2. Write the Code for the Practice, but for draw_rectangle(size.x, size.y) use draw_rectangle(rectangle_sizes.x, rectangle_sizes.y) and run the Code now the turtle should do the jumps but spin on point and dont draw the Rectangles. If you now correct the Code to draw_rectangle(size.x, size.y) the Code works but you get the Error that 1 Rectangle is not the size it should be even with the Solution Code.

**Screenshots**
Screenshots from wrong Code, Correct Code and Solution Code after running in Additional context

**Information about your device :**
 - Operating System: [Windows 10]
 - Browser: [Opera]

**Additional context**
<img width="838" alt="Lesson 20 Practice 2 Wrong Code" src="https://user-images.githubusercontent.com/101862600/158963980-0085fa2b-9f26-415c-95da-437c1927f534.PNG">
<img width="841" alt="Lesson 20 Practice 2 correct Code" src="https://user-images.githubusercontent.com/101862600/158963985-b9391cdf-eef3-4c0a-b1e7-fef5e638c468.PNG">
<img width="889" alt="Lesson 20 Practice 2 Solution Code" src="https://user-images.githubusercontent.com/101862600/158963987-f9b3b317-bced-4cf1-9d0f-6d616af133d1.PNG">

**Comment by pudgypoultry** [comment]
I am also experiencing this same issue, here is my error log
[gdquest-1647667036762.log](https://github.com/GDQuest/learn-gdscript/files/8308637/gdquest-1647667036762.log)
:

**Comment by ShadowMitia** [comment]
Same here, sharing my log in case it helps.
Given solution doesn't work, and own solutions don't work.

[gdquest-1648495436790.log](https://github.com/GDQuest/learn-gdscript/files/8365668/gdquest-1648495436790.log)
.

Operating System: Linux (Pop OS)
Browser: Firefox Nightly100.0a1 (2022-03-26) (64-bit)

**Comment by martindm33** [comment]
I am experiencing the same issue. By going back to the lesson and doing both practices again the solution code worked for me. Log below

[gdquest-1648722753592.log](https://github.com/GDQuest/learn-gdscript/files/8388494/gdquest-1648722753592.log)
.

**Comment by NathanLovato** [comment]
Could you guys please try again with the latest staging build and tell me if the solution code still shows up as incorrect?

Here's the direct link: https://gdquest.github.io/learn-gdscript/staging/#course/lesson-20-looping-over-arrays/practice-clsFcSrG.tres

When doing so, please click on your browser's URL bar and press Ctrl Shift R to clear the page's cache. Otherwise, it may reload the version of the app you last used and that still has the bug.

---

Also, this code shouldn't work.

```gdscript
func run():
	for size in rectangle_sizes:
		draw_rectangle(rectangle_sizes.x, rectangle_sizes.y)
```

The function expects a decimal value but this code tries to pass an array.

In the Godot editor, this will trigger an error, but in the browser, it seems the array gets converted to a value of 0 when used as an invalid argument type. 

Anyway, hopefully, the more important issue of the practice not passing with the correct code should be solved. It's working fine on my end.

**Comment by NathanLovato** [comment]
Got some people to test this, seems it's fixed already. Please let me know if it's not and we'll look into it again.

**Comment by ShadowMitia** [comment]
Confirming it's workig for me! Thanks!
