### ISSUE TITLE
Disabled buttons are hard to spot

### ISSUE THREAD

**Issue by dialmove** [GDQuest/learn-gdscript#56]
**Is your feature request related to a problem? Please describe.**
The styling of disabled buttons (like the "Skip" button in quizzes) is hard to spot, as it's too similar to the active buttons like "Submit" (bluish-gray on bluish-gray on both). Button states look like the inverse-video of each other, but it is not clear which of the two styles correspond to the disabled state.

![image](https://user-images.githubusercontent.com/3824360/147697221-04fc8038-c391-4faa-b304-4c30c68094e3.png)

**Describe the solution you'd like**
Disabled buttons should have much less contrast, probably by writting the font in a lighter gray color:

![image](https://user-images.githubusercontent.com/3824360/147697165-467bede6-1db7-43ab-8d67-bcf8f65e9054.png)

It would also help if enabled buttons changed the pointer to the "hand" icon on mouse over, and disabled buttons did not.

**Comment by maranr** [comment]
I would have to agree with this but would go one step further. The submit and practice buttons don't seem like active buttons to me. I assumed they were in the disabled state due to the muted colors. I would make them more obviously active if they are. Buttons need to be clearly active or disabled. In this case they are two simlar.
