### ISSUE TITLE
Lesson 3 explanation of radians is very confusing

### ISSUE THREAD

**Issue by ghost** [GDQuest/learn-gdscript#591]
The "What are radians?" text box in Lesson 3 was very confusing to me. I can't really give a suggestion as to how this could be fixed, you might want to ask someone who's familiar with teaching this concept for math purposes about that, but I can at least say that the phrasing of "To get the angle in radians, you take the circle's radius and wrap it around the circle." was especially confusing and had me stuck on it for a bit because to me the wording of "wrap it around the circle" sounds like you're wrapping it around the entire circle (which of course isn't possible to do with just the circle's radius). I _think_ what was meant is that you take the radius and measure the same distance out of the circle's circumference.

Maybe someone well-versed in math who knows how to simplify and teach those concepts well could redo that text box, but otherwise I'd recommend that you consider just removing the "How do radians work exactly?" part. It's not necessary information to have for a beginner and you don't want to scare off people who read that and don't understand it.

I would also advise showing how to convert degrees to radians rather than just radians to degrees, as the former calculation is what I would imagine most people need (since they're used to degrees and need to tell the computer what amount of radians to use rather than the other way around). I would also change the text "And 2 * PI is a full turn" to "And 2 * PI radians is a full turn", just for that little bit of extra clarity.

**Comment by NathanLovato** [comment]
Thanks for the reports. Please don't make assumptions about what would or wouldn't work for other people or beginners because they'll often be incorrect. We gathered feedback from numerous beginners making this course, and what is difficult for them or not would surprise you.

That's why we always ask people to just tell us about their personal experiences.

Are you already an experienced developer or just starting out? And did you personally have trouble understanding this note?

**Comment by NathanLovato** [comment]
Superseded by #671 which suggests specific changes/improvements
