### ISSUE TITLE
Lesson 22 - Cell Coordinate to World Coordinate Math Explanation

### ISSUE THREAD

**Issue by p0lrr** [GDQuest/learn-gdscript#643]
![content_suggestion](https://user-images.githubusercontent.com/112536049/187854959-9649c8a7-6412-493b-9dd7-fe4d62afa76d.png)
**Issue description:**
The math used for the conversion from cell coordinate to global coordinate is not explained. A suggestion I have is to add a simple explanation why the cell coordinate is multiplied by its size then added to half its size. Other than that, lesson 22 is very informative.

**Comment by JAlbair** [comment]
Up until Lesson 22, things have been going great! Hitting #22, I felt quite lost and I think it's because the math is not explained. 

Even here: 
![image](https://user-images.githubusercontent.com/110397580/188328825-8435a2ff-e93c-4fbe-a6da-2e55b06da913.png)
I actually can understand the math (I understand the values that are output), but I don't understand WHY we are doing this. 
The practice in 22, even after looking at the solution, is not helpful to me, for this reason.
