### ISSUE TITLE
Lesson 26 - Solution in Lesson

### ISSUE THREAD

**Issue by p0lrr** [GDQuest/learn-gdscript#645]
**Issue description:**
The solutions for both exercises are included in the examples of lesson 26.

**Comment by NathanLovato** [comment]
That's intentional. Most of the app is like this, I think. Practices often reuse code more or less directly from examples, with some minor tweaks. There's already a major cognitive load for someone completely new to programming, so we're using a couple of tricks like this to make it possible for a wide range of neophytes to complete the course. We start to make practices more challenging in our course Learn to Code with Godot, and we do this gradually (until it gets really challenging and you have to code things on your own).

Thanks for the reports by the way, much appreciated.

**Comment by p0lrr** [comment]
> That's intentional. Most of the app is like this, I think. Practices often reuse code more or less directly from examples, with some minor tweaks. There's already a major cognitive load for someone completely new to programming, so we're using a couple of tricks like this to make it possible for a wide range of neophytes to complete the course. We start to make practices more challenging in our course Learn to Code with Godot, and we do this gradually (until it gets really challenging and you have to code things on your own).
> 
> Thanks for the reports by the way, much appreciated.

Ok, thank you so much.
