### ISSUE TITLE
Use of the word "label"

### ISSUE THREAD

**Issue by golddotasksquestions** [GDQuest/learn-gdscript#69]
**Issue description:**
"Label" in Godot already has a distinct meaning and purpose as a text node.

Using the world "label" in context of a function or variable is irritating and imho should be reserved for the Label node.
While "container" also exists as nodes, I believe they work much better as mental image when it comes to variables. Variables are like boxes (=container) you can put variable things into. You can then carry this container to other places in your script open it and look inside, print it's contents, add or remove things to it, or swap the contents out with different things.

**Example Lesson 5**:
"The parameter name is always a label you use to refer to a value"

Instead I would simply say: 
"The parameter is a variable which only exists within this function" (variables imho should really be explained before functions)

Q: "What is a function parameter?"
A: "A label you give a value function the function receives"

The correct answer to this is highly confusing on multiple levels. First off, parameters have nothing to do with labels, they are local variable. 
Secondly I belive "give a value _function_ to function receives" might be a typo but even if replaced by "A variable with a value the function receives", I would not understand much as a complete programming beginner.
I would word the answer like this:
A: "A variable which exists only within this function. It's value is set when the function is called".

Again, I would highly suggest to explain variables before functions.

**Example Lesson 6**:
"variables are labels you use to keep track of values."

Imho better wording would be:
"variables are like containers which can hold any value".

to further an intuitive understand maybe also add:
"if variables are empty, the value they contain is Null."

Q: "What's a variable?"
A: "A label you use to keep track of a value that can change"

This is again has potential to be highly confusing once you learn about the existing of Label nodes. Beginners might first assume Lable nodes to be some kind of variable node or exist to hold values that can change.

I would propose instead:

Q: "What's a variable?"
A: "A container to hold a value that can change."

**Lesson 7**:

"Variables are like labels"
No, they are not at all like labels. The are not like labels you find on a box or on a jar or on a piece of clothing. Label nodes in fact are much more like the labels you find on a box or on a jar or on a piece of clothing.
Variables on the other hand are much more like the box or the jar itself, rather than just the label. They contain something. You can give them any arbitrary name. But they can contain all kinds of things, unless you create a variable (box/container) meant for only specific things. If so, you need to specify what the variable should contain by strictly typing it out: using strictly typed GDScript.

"It has an important consequence. In GDScript you can stick that label to and to any other value."
This is not what is happening from a GDScript users perspective: As a GDScript user, you only assign values to variables, never the other way round. You don't "stick a variable on a value", what you do is "you stick the value on a variable".  Or worded better: "You first create the container by defining it, then you put the value into the container".

**Comment by NathanLovato** [comment]
You can write short reports, I understand the idea.

Please keep in mind this lesson is for absolute beginners.

They don't know Godot's nodes yet so there shouldn't be confusion with the node.

Absolute beginners are the target audience, so we need to write in a way that works for them and ensure they understand things. This analogy works well for that audience.

More importantly, talking about labels is correct in the context. In python and dynamic GDScript, variables are like labels you move onto different values.

In GDScript, when using strong typing, you could say variables work more like containers. When we get there we'll explain that.

Under the hood, identifiers work like lookup tables. 

When you write:

```
var health = 100
health = "full"
```

You effectively make the name health point at different values in the computer's memory.

That's why we can say it's like moving a product label from one product to another in a shop.

If you look at python courses you'll find the same analogy for the same reasons: clear for beginners, correct for dynamic code.

**Comment by golddotasksquestions** [comment]
Under the hood it's all pointers. That's labels. 
But like you say this app is for absolute beginners. That's the whole reason for my argument. My argument is the concept of a label you stick onto a value like a name that is used as pointer to a place in memory might be more correct, but the visual metaphor of a container you can put anything inside is more easily understood by absolute code beginners and it also matches how variables are used in GDScript. Noone uses variables like labels in GDScript.

**Comment by NathanLovato** [comment]
That's taking only a small part of what I wrote. You know we've been teaching for a long time and taught those analogies, containers and labels for names.

As mentioned in my reply, we use that based on experience teaching to beginners. I've never seen a student misunderstand or struggle with the analogy. I don't know where you got that from.

**Comment by golddotasksquestions** [comment]
>That's taking only a small part of what I wrote and misrepresenting what I said.

I don't know what I'm misrepresenting here, but whatever it is, misrepresenting anything you do or say is definitely not my intention.

>I've never seen a beginner student misunderstand or struggle with the analogy. 
Well now you have seen at least one. 

All I'm trying to say is: If that's how I would have been explained it, it would have taken me a lot longer to make sense of this concept and much longer to develop an intuitive understanding for it's use.

But people are different. What makes or does not make sense for me will be different for others.

However I feel like I have to add: 
I get the impression you don't want this kind of feedback when you counter it with phrases like: "We've been teaching beginners to code for a long time", "the analogy of labels based on experience teaching to beginners", "I've never seen", "If people in the target audience" ... I know all this. What's the point in telling me other than to shut me up?

I have been in the target audience for this app recently, so my memory on the struggle is still very fresh. I know the perspective of someone who knows nothing, having none affiliation to code, as well as where the students are supposed to get to (being able to do basics things in Godot with GDScript). 

I opened these issues because you seem to explicitly ask for this kind of help: https://twitter.com/NathanGDQuest/status/1473301698361888772

Even if you don't see this as valuable feedback on the content, you could at least just accept it as a singular data point instead of arguing against it with arguments that sound to me like "You're wrong, we're doing right, because we have all the experience in teaching beginners."

If you don't want to hear this, then why ask for feedback and proofreading at all?

**Comment by pycbouh** [comment]
We appreciate all the feedback we get, so don't feel discouraged, please. However, at this point we are mostly interested in genuine beginner experience rather than opinions of what that experience would be if you were still a beginner now. We all were beginners at some point, we all can imagine and remember what it was like for us. But it's not what is important right now, that's not what would tell us if the course works or not.

As for more experienced users, we ask to trust our tutors to know how to approach teaching beginners and what should work for most. But, again, to validate it we need genuine first-timers.

**Comment by NathanLovato** [comment]
> I get the impression you don't want this kind of feedback

No, it's more you tend to be assertive and I reply straight.

We took the data point, no worries about that. As I last told you:

> If people in the target audience do happen to struggle with it, then I'll happily revise the lessons.

In other words, if beginners confirm what you wrote above, we'll make the change.

As @pycbouh and I said, when it comes to how clear the lessons are, we'd like more feedback from people who are using the app to learn to code right now.

> I don't know what I'm misrepresenting here

I'm sure it's not intentional and I know you come with good intentions. You summarized my post as:

> Under the hood it's all pointers.

I don't mean under the hood. In dynamic code, variables work like labels you move onto different values at a high level.

---------------

Please allow me to rephrase and summarize my general answer to your feedback.

In GDScript (or python or javascript), you can view both variables as labels you move around or as containers you put things into. Both analogies work. In our experience teaching both of these, people understand them. I have yet to see a beginner struggle with either.

In the course, we will cover and use both. I don't think we should drop the label analogy, but if beginners raise issues about that, we will replace it.
