### ISSUE TITLE
Lesson 11 "Moving in a Circle Using Delta" passes with wrong code

### ISSUE THREAD

**Issue by Maltavius** [GDQuest/learn-gdscript#748]
**Describe the bug**
The lesson passes with wrong solution

**To Reproduce**
Enter lesson
Write:
`func _process(delta):
	rotate(2*delta)
	move_local_x(delta,100)`

**Expected behavior**
This moves in a circle but not a 100 offset circle.

**Screenshots**
![image](https://user-images.githubusercontent.com/10133945/205495585-21883c6a-84fb-429e-ace9-6b73bd93041b.png)

**Information about your device (please complete the following information):**
 - Operating System: Linux
 - Browser: Firefox
 - Using this url: https://gdquest.github.io/learn-gdscript/staging/#course/lesson-11-time-delta/

**Additional context**

**Comment by NathanLovato** [comment]
This one is interesting because there should be a type error when calling `move_local_x(delta,100)`, but it seems the GDScript compiler converts the value `100`.

Technically with your code the robot is actually kind of moving in a circle, it is just at the circle is very tiny because you use `delta`.

Anyway I'll add a mini fix to this issue
