### ISSUE TITLE
Some examples' code is not explicit and comprehensive

### ISSUE THREAD

**Issue by Simplifier** [GDQuest/learn-gdscript#81]
- What does [=20] mean? Is it real GDScript syntax? 
![Godot Live Editor — Яндекс Браузер 2022-01-02 02 0](https://user-images.githubusercontent.com/3374612/147861985-133f8770-a8b9-4432-b785-a59cfdf74f3d.png)

If it's not, maybe it's better to call the function explicitly. Because your strange syntax can confuse students.
```python
func draw_square(size):
	move_forward(size)

draw_square(20)
```

- Functions in tasks also aren't called anywhere. I'd prefer it if they were called explicitly.

- I can't comprehend, how the following example works. I guess, it lacks some important details. My intuition tells me, that some function should be called after changing a value to apply that change or something like this
![Godot Live Editor — Яндекс Браузер 2022-01-02 02 3](https://user-images.githubusercontent.com/3374612/147862293-a857a282-6640-4f78-b272-1fafbc65d5f6.png)

I think, examples should be more obvious and closer to reality. Explicit is better than implicit

**Comment by NathanLovato** [comment]
Are you completely new to programming or do you already have programming experience?

**Comment by xix-xeaon** [comment]
I agree that the [=20] is confusing, but I think it's mostly since it's mixed in with the code. How about floating the same information to the right so that it's clear that it's not part of the code. The square brackets wouldn't be needed, could use a different font/size maybe in a "pill"-style box. Hover could expand it and show the name as well like size=20.

**Comment by NathanLovato** [comment]
Yes, I think even that replacing the parameters in a function call would be ideal. It's just that in this example we don't show the call. We could show the value on mouse hover in a pill or something, clearly. We'll figure out a way to improve this UX bit. I'll open a dedicated issue for that right away.

**Comment by Simplifier** [comment]
> Are you completely new to programming or do you already have programming experience 

I have, but I'm new at GDScript

> The reason we don't show function calls early on is that this is invalid GDScript

Oh, it makes things more complicated. Maybe it's better to just add a new interim lesson, where you explain, that `_ready()` function is an entry point? "Magical" things increase cognitive load instead of decreasing it, as I see it. Because it's harder to understand, what's going on

**Comment by Dinock** [comment]
I found another code example which can be confusing or misleading for beginners.

In lesson 6 it is shown how to define a function with multiple parameters. It is clearly shown with the help of a symbol that there needs to be a space between `func` and the name of the function.

But there is also a space after the comma to separate the parameters, which is _not_ represented by a symbol.
Then in the following code example there is a space after the comma (see also screenshot below).
`func move_local_xy(offset_x, offset_y):`

This can lead to confusion because it is not entirely clear if a parameter has to be separated from another parameter with a space or not, or if this even could be optional.

Screenshot of the code example in lesson 6:
![Leerzeichen_nach_Komma_oder_nicht-lesson6](https://user-images.githubusercontent.com/54438803/148822906-38f77213-0ead-4d3e-a439-0467903d16f3.png)

**Comment by NathanLovato** [comment]
@Dinock are you a beginner, and did you get confused by the example?

I need to be sure that in practice, people in the target audience do get confused, and that we're not assuming. Because extra explanations add cognitive load and can also cause confusion.

**Comment by Dinock** [comment]
Yes, I am a beginner and I got a bit confused. But maybe that is also just me, it's just one experience from a single person. I think it would be important to gather some more information from other beginners, if they found it confusing or irritating.

Maybe it would also help if there would be just a small note or a single sentence which points out if the space between different parameters is optional or mandatory. At least this would have helped me a lot and I think this would not bloat the cognitive load too much.

**Comment by NathanLovato** [comment]
There are several issues mixed in here with different scopes, so I created separate tasks to tackle each of them:

- #212
- #213 
- #84 

They supersede this discussion.
