### ISSUE TITLE
Error in lesson 17 

### ISSUE THREAD

**Issue by csebleder** [GDQuest/learn-gdscript#820]
I know it's not the goal here but when i try to set the x coordinate using while loop the program gives an error that says the script verifier didn't catch. 

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'lesson 17 practice part '
2. Write the code 'func move_to_bottom():
	while cell.y<board_size.y:
		cell.y+=1
	while cell.x<board_size.x:
		cell.x+=1'
3. See error

**Expected behavior**
Explaining the reason of the error or saying it's not the wanted action.

 - Operating System: Windows 11

![Ekran görüntüsü 2023-05-17 235308](https://github.com/GDQuest/learn-gdscript/assets/133918542/b6d62232-a9f0-4a08-958a-ae3f9f30aee7)

[2023-05-17-23-37.log](https://github.com/GDQuest/learn-gdscript/files/11502494/2023-05-17-23-37.log)

**Comment by Visnicio** [comment]
I might be wrong in my statement, so pleaser correct me if I am.
But AFAIK, the compiler only shoutout precise error logs on predefined errors, AKA: Code that does not pass the `Checks`

Also, I'm not sure if GDScript is capable of handling the `cell.y<board_size.y` syntax since cell was not declared anywhere, nor a part of a loop, but I guess we will need confirmation of someone inside the development team to confirm

**Comment by NathanLovato** [comment]
@csebleder, did you run the app from the Godot editor? Or was it the Windows build from itch.io?

If it's the former, the behavior is normal - as mentioned in the readme, it's not meant to be followed from Godot. If it's the latter, this might well be linked to #864

**Comment by Wolfy7** [comment]
Probably same issue as #961 (multiple while loops). Fix -> https://github.com/GDQuest/learn-gdscript/pull/999

**Comment by NathanLovato** [comment]
This was fixed by https://github.com/GDQuest/learn-gdscript/pull/999
