### ISSUE TITLE
Chapter 18 in the "range()" function.

### ISSUE THREAD

**Issue by gagupa** [GDQuest/learn-gdscript#853]
Good evening, I believe I have found a logic error in Chapter 18 in the "range()" function.
In the first part it is taught that "range()" is a number "n -1"

**That is, it AUTOMATICALLY subtracts "1" from the value placed in parentheses.**

so a range(3) value represents "0, 1 and 2"

But in the next part, when the usage comparison between "while" and "for" is done, I found this possible error.
![error](https://github.com/GDQuest/learn-gdscript/assets/12751629/715da0e9-5df3-4156-8905-28211082673f)

**if the value of "board_size.x" is 3,** it doesn't make sense to use "-1" there.
because when doing that, I would actually be generating a "range(2) and not (3) as it should be correct, **and this even interferes in the next lesson, because I had to put the "-1" to validate the class.**

**my logic:**
i have 3 cells _(like sample in image)_
board_size.x = 3
board_size.x-**1** = 2
now range(2)
result of range (2) is 0 and 1

PS: I'm not a developer, I'm still learning.
I hope I was able to express myself properly to report the "possible" error I found.

**Comment by NathanLovato** [comment]
This code is to move the robot. If the grid is three cells large, the robot starts on the first cell, so to reach the edge of the grid (the third cell), the robot should move only twice. That's why we subtract one and reduce the number passed to the range here. Otherwise, the robot would move three times and move outside of the grid.
