### ISSUE TITLE
Lesson 18: Explanation of Arrays

### ISSUE THREAD

**Issue by FinnMM** [GDQuest/learn-gdscript#897]
Arrays themselves are _not_ a value type, as stated otherwise in the lesson. This is very misleading to beginners and should be fixed right away.

https://docs.godotengine.org/en/stable/classes/class_array.html
https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#built-in-types

I just want to say that I am impressed with these lessons overall so far. I am more accustomed to C-style syntax, so it's very useful stuff! :)

**Comment by NathanLovato** [comment]
A value is any entity the program can manipulate, anything you can assign or retrieve through a variable. Any data structure can be called a value.

More importantly, the details of terminology go way over beginners' heads, so it isn't really misleading or useful to them.

I don't know what problem you imagine this wording could cause. Is it about things being passed by value versus reference? If so, learners in this series would have no idea that this exists in the first place. Only already experienced developers would.

**Comment by FinnMM** [comment]
Thanks for writing.

Hmm, depends on the data structure whether it is a reference or value, at least to me. Maybe it's a useful abstraction (in thought) to call an array a value rather than an address or reference? If GDScript does with arrays what it does with strings (copy on write), then it wouldn't matter at all. Maybe it doesn't matter after all? Your call. You have some vision for where you're leading everyone with your lessons, so just follow that, and keep up the awesome work! :)

It doesn't have to be in jargon. I think a quick nod at copies versus 'containers' is enough. The problem is that a beginner might get confused over passing or assigning arrays around and thinking it's a deep copy by default. At least a warning about it not being a copy of the values inside it would probably suffice.

For example, as a quick demonstration for newbies:
    var arr1 = [1, 2, 3]
    var arr2 = arr1
    arr2[0] = 5
    for i in arr1:
    	print(i)
And really encourage them to try it for themselves. The devil is in the details, so it is worth being aware of it at least, even if they don't know how it works under the hood exactly quite yet. That is my philosophy at least. Again, your call.

I'm by no means an experienced developer or even a developer at all by the way.

I'll close this now, so I don't bother you any further. Good luck to you.

**Comment by NathanLovato** [comment]
I understand, and definitely agree that content dedicated to passing by value versus reference is really important. I think this would warrant a dedicated lesson, and it's also something I would rather teach later in people's learning journey, at a point where we can give them a concrete example of why the difference matters.

When working in a framework like Godot, it mostly becomes a concern when you start mutating function arguments from within the function's body for performance concerns, which is something already quite advanced (compared to a language like C where it's often necessary because the language doesn't handle references automatically for you).

Another case where people could get into trouble with this in a high-level language like GDScript is when coding recursive functions. But there also it'd be only if mutating the function parameter as opposed to mutating a property of the current class.

I think that both of these issues are uncommon in an environment like Godot, that does so much for you.

And please don't think you're bothering me! I appreciate you taking the time to share detailed feedback.
