### ISSUE TITLE
script with str function call fails

### ISSUE THREAD

**Issue by Kevar** [GDQuest/learn-gdscript#979]
**Describe the bug**
When using the str() function in the first exercise, running the script fails

**To Reproduce**
Steps to reproduce the bug:
1. Go to the first exercise
2. Paste the following script :
`func _ready():`
`	var i = 0`
`	print(str(i))`
3. Run the script
4. The output shows an error

**Expected behavior**
The output should show the text "0"

**Screenshots**
![image](https://github.com/user-attachments/assets/33031ad6-84dc-4772-bb71-b5f2b03dedde)

**Generated log:**
[gdquest-1724254390736.log](https://github.com/user-attachments/files/16694680/gdquest-1724254390736.log)

**Comment by Wolfy7** [comment]
The problem lies in the use of the greedy quantifier .*?, which captures as little as possible, but in your case closes up to the first closing bracket.

(script_replacements)
`\\b(?<command>print)\\((?<args>.*?)\\)`

A simpler solution could be to adapt the expression so that it explicitly searches for the appropriate closing bracket.
See PR https://github.com/GDQuest/learn-gdscript/pull/997 which would do this.
