### ISSUE TITLE
Lesson 1: Turkish translation is missing

### ISSUE THREAD

**Issue by demirelio** [GDQuest/learn-gdscript#989]
![image](https://github.com/user-attachments/assets/f399429b-335c-43f0-acda-76f104baae36)

The text under the title "GDScript ile kodlamayi ogreneceksiniz" in English language for Turkish version. I couldn't find how can i add the Turkish so, i can provide the Turkish below for the text:

--Turkish translation for the content --
Bu kursta GDScript programlama dilini öğreneceksiniz. (GDScript isminin açılımı Godot Script'tir. Script ise programlama dünyasında "bilgisayarın anlayabileceği şekilde düzenlenmiş komutlar" anlamına gelir. Yani GDScript Godot oyun programının anlayacağı komutları yazmamızı sağlayan dildir.)

Bu programlama dili oyun geliştiriciler için yine oyun geliştiriciler tarafından oluşturulmuştur. GDScript'i Godot oyun motorunda oyun ya da programlar oluşturmak için kullanabilirsiniz.

Bu programlama dili Dome Keeper ve Brotato gibi oyunları kodlarken de kullanılmıştır.

Tesla mühendisleri de arabaların konsol ekranlarında bu dili kullanmaktadır.

**Comment by NathanLovato** [comment]
Thanks for the report, closing in favor of tracking this in https://github.com/GDQuest/learn-gdscript-translations/issues/130 - we track translations in this other repository. The next update should bring missing Turkish translations.

**Comment by yilmazdurmaz** [comment]
@NathanLovato actually this part was one of buggy ones.

Although I had translated it long ago, this part is (and some other parts) not fetched to be translated inside the application.

There may exists other similar issues opened in other languages, and unless fixed in recent PRs, it will still be shown in English.

Its place is in Lesson 1 and just after the first quiz question.

**Comment by NathanLovato** [comment]
Yes sure, when the content in the app gets an update, translations do not get continuously updated and integrated automatically so they will always lag behind until the next manual release.

As translations are community contributed and done asynchronously anytime after making changes to the English version of the app, this kind of issue tends to arise.

The way translations often work in games is that you have the English string and then the translation system, at runtime, upon changing the language, swaps the English version with a matching translation in a dictionary. If it does not find a perfect match character by character, it keeps that sentence in English. 

There are several ways to mitigate this, including breaking down the lesson into smaller translation chunks like single sentences instead of paragraphs or groups of paragraphs. I tried doing that at some point but preserving all the existing translations is tricky.

I think the ideal scenario would be to have a different pipeline where new copies of the lesson text get fully baked in the target language at build time, avoiding this runtime translation mechanism entirely. This would ensure that a given translated version of a lesson gets preserved even if a few changes get made to the English version, causing some strings to otherwise not translate. But it's a substantial change that I won't have time to work on anytime soon.

**Comment by NathanLovato** [comment]
Note that as the content of the app has been stabilizing, this issue will become less and less frequent, that is, until we make substantial changes to the English version of the content.

**Comment by yilmazdurmaz** [comment]
@NathanLovato  thanks for clearing, I thought it was done in build time and assumed some parts in the code were bugging 😅

**Comment by yilmazdurmaz** [comment]
Merhaba @demirelio

Geçen sene tüm derslerin çevirilerini yapmıştım, ancak bazı kısımlar yine de ingilizce görünüyordu. Yukarıda Nathan'ın dediğine bakarsak, çeviriler sayfa çalışırken anlık gösterime ayarlıymış, ve sanırım benden sonra arada kod içinden ufakta olsa değişiklik yapılınca program çeviriyi koyacak yeri bulamayıp İngilizce bırakıyormuş.

Kursun güncellenme işleri biraz yavaş gidiyor, çünkü hem neredeyse tamamlanmış bir içeriğe sahip hem de GDQuest'in kendi diğer kurslarıyla da uğraşması gerekiyor (özellikle de ücretli olanlara dikkat vereceklerdir). Bu yüzden bir değişiklik yaparsak yada sorun görürsek beklemekten başka pek bir şey yapamıyoruz. tabi böyle sorun yazılarını yazıp okumalarını beklemek dışında.

Neyse, aşağıdaki link çevirileri yaptığımız yer. Kullanmaya alışmak biraz zaman alıyor ama sonra kolay olduğunu göreceksin.

https://hosted.weblate.org/projects/learn-gdscript-from-zero/-/tr/

Eğer vaktin olursa bir göz atmanı isterim (tabi şu anki güncelemelerin yayınlanmasını beklersen iyi olur). Geçen ay tekrar bir gözden geçirdim ama sadece "sen" yerine "siz" şeklinde ifadeleri biraz değiştirip yazım hatalarıma bakmıştım. Ama yine de kinci bir göz fena olmaz.

Not: Belki oradan Godot'nun kendi belgelerine geçmeyi de düşünebilirsin. O zaman bana bir haber verirsen sevinirim.
